language: cpp
dist: focal

addons:
  sonarcloud:
    organization: "othereum"
    token:
      secure: "Bae9OMFKQWAdawqoTuQB5VPuxDLYZj2ZDI55BZEV7pghF2DKuiRXD7Wnl7V1XHEHZLpIew8PDGL2iZ6WeNd3PS7rslb0G6x9MxEqc16r92XcarHd8Hp5Z4VMu1dcDvhCcZ9u4UPp5eFVbzwcc6rShAMcUz8VbnocWf+c+6jdl9gV93ldEebMCsvVYo2+GTPUb5QrHLxck8uX/AVYNK9pWrnFazFTPo5aKRPmo+nP1oIvRJWURG1wmrWG3roOpM1zomiUtR14RTjXZxm6ZQX5Fkm66vZ3CLvUQi2/TuX/9t7E4sXyNT+rDR08Tdn4YD2WG4lAOKJjS1BfZuOi+LBZX4aeeCRKKHzvn+8aXqVvoLNV+VFyRVYmHbKDM6dWhjut495EDSYYpiyAWhNmdp9ZUPR3Wdw+Q1QWyleMK8kwIMPydaKZBHzKsnR1qN69nXjnN1AGe6q+9aiyf55Ie90P2ZtO8C14uH13J99GAlhgv09uBN8Spy4p7r/t3qVkbZ1HWZUf03HjDvLOY30qRWIq6hhnBKGMwjZdoPa2+fgze1MLMQ72PzWRWXiTm6zzNtkGEv26+SnHOMPTgfXfrMs07+H0uSHqCx0ciYN4U4UFI4jGZJ9CEvQKdGSDvtEeHvH4MAgL+hzkLuqEwB1EnjO6y3Uv6j6P19gxm2JLxpzmGHc="
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal-10 main'
        key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - clang-10
      - clang++-10
      - llvm-10-dev
      - libstdc++-10-dev

script:
  - ./configure
  - build-wrapper-linux-x86-64 --out-dir bw-output cmake --build out/ -- -j
  - sonar-scanner -Dsonar.cfamily.build-wrapper-output=bw-output
