language: cpp
os: linux
dist: focal

addons:
  apt:
    update: true
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - clang++-10
    - cmake
    - libsdl2-dev
    - libglew-dev

env:
  - CMAKE_BUILD_TYPE=Debug
  - CMAKE_BUILD_TYPE=Release

script:
- mkdir -p out && cd out
- cmake -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE -DCMAKE_CXX_COMPILER=clang++-10 ..
- make -j
