language: cpp
compiler: clang
os: linux
dist: focal

addons:
  apt:
  - clang++-10
  - libstdc++-10-dev
  - libsdl2-dev
  - libglew-dev

env:
- CMAKE_BUILD_TYPE=Debug
- CMAKE_BUILD_TYPE=Release

install:
- wget https://github.com/Kitware/CMake/releases/download/v3.18.0/cmake-3.18.0-Linux-x86_64.tar.gz
- tar -xf cmake-3.18.0-Linux-x86_64.tar.gz
- PATH=$PWD/cmake-3.18.0-Linux-x86_64/bin:$PATH

script:
- mkdir -p out && cd out
- cmake -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE -DCMAKE_C_COMPILER=clang-10 -DCMAKE_CXX_COMPILER=clang++-10 ..
- make -j
