language: cpp
dist: focal

addons:
  sonarcloud:
    organization: "othereum"
    token:
      secure: "ohnP2uN/X+CI+8RMo0HlZhXTvQIbAJBmS4VTiMeSt/uSalfwqxAR1X3oXxN9VHCR4lH0TUJoG6MraNM3Y/0CJtTf6IFrBbsxP6W5ymwNq8Ez1MBr5u238EEQlOKTWEKhVhE0+HJx5zXoE13hEInlTc9aLcsJBZstcjPOyvb5yVX75taRRHPDvLuVBYXjA/GUNHX7y34wVuCXhFd/gAv0bwInBoiKRG38yOW184w30aF7CqGaIpAFjw/wAjk/mB3Ag8m0DnfmBWRce+Ju3gREGtiNR7Ok2vi34Z55ZVC8bRo7S+Z1Rt5XNsUULwL0nyPGlu8u3ybm+TbKRlqbS/J93+fXxbNAsxyymS3Oo1L056w7MXWt+k+aAehAvRZDKJyCtFp3Tnh0TskSYrdcbDgKkg3wo1QIOYqTbPRJ3bgxCDpIJUhtH3gN5qcXfUBbG7gNCfSM4fmW+yIk1zcxwSaihItwcpqA2qinu2thHOpIZ2WLZmEBs/YYeJLs5pqW3HjQjL1hdQzmCVICXZWLhwC2nzUp66e5MneMAFDQNRKtpzurvkJBiNyiJeilPUZirVkuW7xlyzZff42KJ82fEYzkD/KmBNd3dsUODRz6Id2SeTXPw9iHCJhfbqDRzUqrUdAAon/8aDLnSlcgMFOESPfLUKQv9B9hY05G2cW+JKqj5gk="
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal-10 main'
        key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - clang-10
      - clang++-10
      - llvm-10-dev
      - libstdc++-10-dev

script:
  - ./configure
  - build-wrapper-linux-x86-64 --out-dir bw-output cmake --build out/ -- -j
  - sonar-scanner -Dsonar.cfamily.build-wrapper-output=bw-output
