language: cpp
compiler: clang

os: linux
dist: focal

addons:
  apt:
  - clang++-10
  - libstdc++-10-dev # For C++20 standard library headers
  - llvm-10-dev # For LTO (LLVMgold.so)
  - libsdl2-dev
  - libglew-dev

env:
- CMAKE_BUILD_TYPE=Debug
- CMAKE_BUILD_TYPE=Release

install:
- ./GetCMake.sh 3.18.1
- PATH=$PWD/cmake-install/bin:$PATH
- ./GetFMOD $FMODUSER $FMODPASS 20010

script:
- mkdir -p out && cd out
- cmake -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE -DCMAKE_C_COMPILER=clang-10 -DCMAKE_CXX_COMPILER=clang++-10 ..
- make -j
