language: cpp
dist: focal

addons:
  sonarcloud:
    organization: "othereum"
    token:
      secure: "L+II54wLHebTc67TMqlI8pKJvOMhwqvETdwIvkDinfdSmUNJC3VzRva1+iaQE867qM3l0rL0LcnoZ6t+MLsHBko8uOEagLpg4CRbrvswxNiT8KFJeo6+S6vqHh8gzC6y+G9/Ryg4f/jyXrn67UGtP5BkJPj6g808BcUGlahzT3dXFrNgmW4I6hLReDWnh45HJAxiFTf1rO6aLYfIRcpWZ6IuQidCQ3kWs9YbgNMnHMsWlabRCpv/prWO0xPdcFxd/PVL8ujC6dC788P0aZ4Bnn6tkNA7gUa1PlwwdxpUM5SdTz8ECyNBMlacmS2JxtyMw0SP6isgmJSoOSasqd4j/3gbLSQ8QDtrSGmYL2wMvtsX3T0NZd/kYx/+IoYG8yon0UZIM8pl+4ld1d4JHbe3KE21ev8OoGURRGayHBZPf9x7iiOCJ6+Mk/Ije80R4MVL9LQlbHtIM9yPfNBLIkjOwf7U1LBD9znincS56H9osmN16/TBjZm56jVS9NQcWXh/D3KgmolPAIYbfWF4VmP33Mu3LzeNzYByYnz4xC9dJ3ER4sYpA1s9mPtX1osAYzaaUCWuFJW7Vl0kE+9Wapdjs6zCbWCC97yPpxJeUyeNDbQIrlifvchppHX8Uu8bHBMVkq1BHm6cGV5tLyXJPNUrIlYNEJwmD+CH2r//DS6uURc="
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal-10 main'
        key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - clang-10
      - clang++-10
      - llvm-10-dev
      - libstdc++-10-dev

script:
  - ./configure
  - build-wrapper-linux-x86-64 --out-dir bw-output cmake --build out/ -- -j
  - sonar-scanner -Dsonar.cfamily.build-wrapper-output=bw-output
